build: Use 'nix develop' for CI lint jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,35 +71,23 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Install Python
-        uses: actions/setup-python@v5
+      - name: Install Nix
+        uses: cachix/install-nix-action@v27
         with:
-          python-version: "3.12"
+          nix_path: nixpkgs=flake:nixpkgs
 
-      - name: Setup poetry cache
-        uses: actions/cache@v4
-        id: cache-poetry
+      - name: Install Cachix
+        uses: cachix/cachix-action@v15
         with:
-          path: ~/.virtualenvs
-          # yamllint disable-line rule:line-length
-          key: ${{runner.os}}-${{ env.pythonLocation }}-${{ matrix.lint.rule }}-v3-${{ hashFiles('**/poetry.lock') }}
-
-      - name: Install and configure dependencies
-        run: |
-          pip install poetry poetry-dynamic-versioning
-          poetry config virtualenvs.in-project false
-          poetry config virtualenvs.path ~/.virtualenvs
-
-      - name: Install package
-        run: poetry install
-        if: steps.cache-poetry.outputs.cache-hit != 'true'
+          name: bow
+          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
 
       - name: ${{ matrix.lint.name }}
         run: |
           if [ "${{ matrix.lint.rule }}" = "scan-sec-deps" ]; then
-            make ${{ matrix.lint.rule }} || (echo "::warning file=scan-sec-deps::Scan dependencies failed with exit code $?.")
+            nix develop .#ci --command make ${{ matrix.lint.rule }} || (echo "::warning file=scan-sec-deps::Scan dependencies failed with exit code $?.")
           else
-            make ${{ matrix.lint.rule }}
+            nix develop .#ci --command make ${{ matrix.lint.rule }}
           fi
         continue-on-error: ${{ matrix.lint.rule == 'scan-sec-deps' }}
 
